server.port=8085

spring.mvc.view.prefix = /WEB-INF/views/
spring.mvc.view.suffix = .jsp
spring.mvc.static-path-pattern=/resources/**

aws.region.name = us-east-1
localstack.endpoint=http://localhost:4566
localstack.docker.service=localstack

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.mongodb.uri=mongodb://localhost:27017/localstackui?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000

kafka.bootstrap.servers=localhost:9092
kafka.docker.service=kafka
kafka.topic.command=/opt/kafka/bin/kafka-topics.sh
kafka.producer.command=/opt/kafka/bin/kafka-console-producer.sh
kafka.offsets.command=/opt/kafka/bin/kafka-get-offsets.sh

gcp.project.id=localstack-ui
gcp.pubsub.host=localhost
gcp.pubsub.port=8681
gcp.pubsub.docker.service=gcp-pubsub
gcp.pubsub.disable.credentials=true
gcp.pubsub.api.endpoint=http://localhost:8681/
gcp.storage.endpoint=http://localhost:4443
gcp.storage.docker.service=gcp-storage
gcp.firestore.host=localhost
gcp.firestore.port=8787
gcp.firestore.endpoint=http://localhost:8787
gcp.firestore.docker.service=gcp-firestore
gcp.firestore.auth.token=owner

mock.servers=
